import { ROLE_KEYS, type RoleKey } from './roles.constants'

export const PERMISSION_KEYS = {
  DEPARTMENTS_READ: 'departments.read',
  DEPARTMENTS_MANAGE: 'departments.manage',
  MEMBERS_READ: 'members.read',
  MEMBERS_MANAGE: 'members.manage',
  OPERATIONS_READ: 'operations.read',
  OPERATIONS_MANAGE: 'operations.manage',
  WORKFORCE_READ: 'workforce.read',
  WORKFORCE_MANAGE: 'workforce.manage',
  EQUIPMENT_READ: 'equipment.read',
  EQUIPMENT_MANAGE: 'equipment.manage',
  MAINTENANCE_READ: 'maintenance.read',
  MAINTENANCE_MANAGE: 'maintenance.manage',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_MANAGE: 'inventory.manage',
  QC_READ: 'qc.read',
  QC_MANAGE: 'qc.manage',
  INCIDENTS_READ: 'incidents.read',
  INCIDENTS_MANAGE: 'incidents.manage',
  ANALYTICS_READ: 'analytics.read',
} as const

export type PermissionKey = (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS]

export const ALL_PERMISSION_KEYS: PermissionKey[] = Object.values(PERMISSION_KEYS)

/**
 * Default permission set per system role, seeded once into
 * `role_permissions` by `pnpm run db:seed` (safe and additive to re-run
 * after any phase that adds keys or changes these defaults).
 * Authorization checks (PermissionsGuard) read from the database at
 * request time, not from this map.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  [ROLE_KEYS.ORG_ADMIN]: ALL_PERMISSION_KEYS,
  [ROLE_KEYS.LAB_MANAGER]: [
    PERMISSION_KEYS.DEPARTMENTS_READ,
    PERMISSION_KEYS.MEMBERS_READ,
    PERMISSION_KEYS.OPERATIONS_MANAGE,
    PERMISSION_KEYS.WORKFORCE_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.MAINTENANCE_MANAGE,
    PERMISSION_KEYS.INVENTORY_MANAGE,
    PERMISSION_KEYS.QC_MANAGE,
    PERMISSION_KEYS.INCIDENTS_MANAGE,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
  [ROLE_KEYS.LAB_SCIENTIST]: [
    PERMISSION_KEYS.OPERATIONS_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_READ,
    PERMISSION_KEYS.MAINTENANCE_READ,
    PERMISSION_KEYS.INVENTORY_READ,
    PERMISSION_KEYS.QC_MANAGE,
    PERMISSION_KEYS.INCIDENTS_MANAGE,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
  [ROLE_KEYS.TECHNICIAN]: [
    PERMISSION_KEYS.OPERATIONS_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_READ,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.MAINTENANCE_READ,
    PERMISSION_KEYS.INVENTORY_READ,
    PERMISSION_KEYS.QC_READ,
    PERMISSION_KEYS.INCIDENTS_READ,
  ],
  [ROLE_KEYS.QUALITY_OFFICER]: [
    PERMISSION_KEYS.OPERATIONS_READ,
    PERMISSION_KEYS.QC_MANAGE,
    PERMISSION_KEYS.INCIDENTS_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_READ,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
  [ROLE_KEYS.INVENTORY_MANAGER]: [
    PERMISSION_KEYS.INVENTORY_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_READ,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
  [ROLE_KEYS.MAINTENANCE_ENGINEER]: [
    PERMISSION_KEYS.OPERATIONS_READ,
    PERMISSION_KEYS.MAINTENANCE_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.INCIDENTS_READ,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
  [ROLE_KEYS.IT_ADMIN]: [
    PERMISSION_KEYS.DEPARTMENTS_MANAGE,
    PERMISSION_KEYS.MEMBERS_MANAGE,
    PERMISSION_KEYS.WORKFORCE_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_READ,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
  [ROLE_KEYS.VIEWER]: [
    PERMISSION_KEYS.DEPARTMENTS_READ,
    PERMISSION_KEYS.MEMBERS_READ,
    PERMISSION_KEYS.OPERATIONS_READ,
    PERMISSION_KEYS.WORKFORCE_READ,
    PERMISSION_KEYS.EQUIPMENT_READ,
    PERMISSION_KEYS.MAINTENANCE_READ,
    PERMISSION_KEYS.INVENTORY_READ,
    PERMISSION_KEYS.QC_READ,
    PERMISSION_KEYS.INCIDENTS_READ,
    PERMISSION_KEYS.ANALYTICS_READ,
  ],
}
